import tempImgHouse from './assets/svg/temp-house.jpg';
import { CardProps } from './interfaces';

export const data: CardProps[] = [
  {
    adress: '3014 Tree Frog Lane, Lenexa, Missouri',
    title: 'Realy big house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.stackexchange.com/',
    email: 'lamoidoitrese-9866@yopmail.com',
    phone: '(573) 642-8896',
    price: '1 000 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247080,
  },
  {
    adress: '4902 Marcella Ave, Laredo, Texas(TX), 78041',
    title: 'Small house for small family',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.realtor.com/',
    email: 'muvoilamocei-4662@yopmail.com',
    phone: '(956) 724-7777',
    price: '20 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247081,
  },
  {
    adress: '555 Roark Ln, Vicco, Kentucky(KY), 41773',
    title: 'Nice view house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.zillow.com/',
    email: 'koddaceuxuja-6405@yopmail.com',
    phone: '(606) 476-8863',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247084,
  },
  {
    adress: '8211 Woodview Drive, Onalaska, Wisconsin(WI), 54650',
    title: 'Scary ghost house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.yelp.com/',
    email: 'gezeiluppaje-7444@yopmail.com',
    phone: '(608) 783-5225',
    price: '200 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247067,
  },
  {
    adress: '3406 Vinton St, Hopewell, Virginia(VA), 23860',
    title: 'Nice home for retirees',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.ranker.com/',
    email: 'wussikeucesso-4003@yopmail.com',
    phone: '(304) 565-3540',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247088,
  },
  {
    adress: '8211 Woodview Drive, Onalaska, Wisconsin(WI), 54650',
    title: 'Scary ghost house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.yelp.com/',
    email: 'gezeiluppaje-7444@yopmail.com',
    phone: '(608) 783-5225',
    price: '200 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247080,
  },
  {
    adress: '3406 Vinton St, Hopewell, Virginia(VA), 23860',
    title: 'Nice home for retirees',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.ranker.com/',
    email: 'wussikeucesso-4003@yopmail.com',
    phone: '(304) 565-3540',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 165134224704,
  },
  {
    adress: '2240 Pinehurst Rd, Snellville, Georgia(GA), 30078',
    title: 'Poor and broken house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.quizlet.com/',
    email: 'subidirako-4730@yopmail.com',
    phone: '(608) 783-5225',
    price: '100',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247086,
  },

  {
    adress: '555 Roark Ln, Vicco, Kentucky(KY), 41773',
    title: 'Nice view house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.zillow.com/',
    email: 'koddaceuxuja-6405@yopmail.com',
    phone: '(606) 476-8863',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247055,
  },
  {
    adress: '8211 Woodview Drive, Onalaska, Wisconsin(WI), 54650',
    title: 'Scary ghost house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.yelp.com/',
    email: 'gezeiluppaje-7444@yopmail.com',
    phone: '(608) 783-5225',
    price: '200 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247123,
  },
  {
    adress: '3406 Vinton St, Hopewell, Virginia(VA), 23860',
    title: 'Nice home for retirees',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.ranker.com/',
    email: 'wussikeucesso-4003@yopmail.com',
    phone: '(304) 565-3540',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247089,
  },
  {
    adress: '2240 Pinehurst Rd, Snellville, Georgia(GA), 30078',
    title: 'Poor and broken house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.quizlet.com/',
    email: 'subidirako-4730@yopmail.com',
    phone: '(608) 783-5225',
    price: '100',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247010,
  },
  {
    adress: '555 Roark Ln, Vicco, Kentucky(KY), 41773',
    title: 'Nice view house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'https://www.zillow.com/',
    email: 'koddaceuxuja-6405@yopmail.com',
    phone: '(606) 476-8863',
    price: '100 000',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247079,
  },
  {
    adress: '2240 Pinehurst Rd, Snellville, Georgia(GA), 30078',
    title: 'Poor and broken house',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    link: 'http://www.quizlet.com/',
    email: 'subidirako-4730@yopmail.com',
    phone: '(608) 783-5225',
    price: '100',
    date: '2000-01-01',
    area: '100',
    typeAdd: 'sale',
    isReady: true,
    currency: '$',
    img: tempImgHouse,
    isFavorite: false,
    adCreationDate: 1651342247077,
  },
];
